id: Slack Load Testing Worker
version: -1
name: Slack Load Testing Worker
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 2fd72c68-fc9c-4618-86e6-664741528749
    type: start
    task:
      id: 2fd72c68-fc9c-4618-86e6-664741528749
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 00cd44d8-0695-4b6c-8258-1c43a5bb8427
    type: regular
    task:
      id: 00cd44d8-0695-4b6c-8258-1c43a5bb8427
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: c90cd9d7-b17b-4346-8a3b-d133eb1b0af2
    type: regular
    task:
      id: c90cd9d7-b17b-4346-8a3b-d133eb1b0af2
      version: -1
      name: GetTime
      description: |
        Retrieves the current date and time.
      scriptName: GetTime
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: b1bc4b4b-2d3a-4966-8b17-647990b43a3a
    type: regular
    task:
      id: b1bc4b4b-2d3a-4966-8b17-647990b43a3a
      version: -1
      name: mirror-investigation
      description: Mirrors the investigation between Slack and the Demisto War Room.
      script: SlackV3|||mirror-investigation
      type: regular
      iscommand: true
      brand: SlackV3
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      channelName:
        complex:
          root: TimeNowUnix
          transformers:
          - operator: Stringify
      using:
        simple: SlackV3_LoadTester
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 2a84272f-db82-4c51-8f46-cabc4e0a7787
    type: regular
    task:
      id: 2a84272f-db82-4c51-8f46-cabc4e0a7787
      version: -1
      name: Burst Test
      scriptName: SlackBurst
      type: regular
      iscommand: false
      brand: SlackV3
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      dos_endurance:
        simple: "false"
      quantity:
        simple: "30"
      slack_channel:
        complex:
          root: TimeNowUnix
          transformers:
          - operator: Stringify
      slack_instance:
        simple: ${incident.name}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 75e3a5db-ffb9-42e1-817c-c9f2d15f9079
    type: regular
    task:
      id: 75e3a5db-ffb9-42e1-817c-c9f2d15f9079
      version: -1
      name: slack-invite-to-channel
      description: Invites users to join a channel.
      script: SlackV3|||slack-invite-to-channel
      type: regular
      iscommand: true
      brand: SlackV3
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      users:
        simple: AndrewS
      using:
        simple: SlackV3_LoadTester
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: a7890651-8ada-43b4-8571-45222ba269db
    type: regular
    task:
      id: a7890651-8ada-43b4-8571-45222ba269db
      version: -1
      name: GetCurrentEntries
      scriptName: GetCurrentEntries
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      incident_id:
        simple: ${incident.id}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: d66b6d1d-a59c-420a-8d8e-04625ac7026a
    type: regular
    task:
      id: d66b6d1d-a59c-420a-8d8e-04625ac7026a
      version: -1
      name: Sleep
      description: Sleep for X seconds
      scriptName: Sleep
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      seconds:
        simple: "300"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 1
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 9d79d155-8840-4664-88df-965ca8d07d7b
    type: condition
    task:
      id: 9d79d155-8840-4664-88df-965ca8d07d7b
      version: -1
      name: Validate Quantity of Mirror Ins
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "13"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualNumber
          left:
            value:
              complex:
                root: LatestEntries
                transformers:
                - operator: getField
                  args:
                    field:
                      value:
                        simple: ${ValidationKey}
            iscontext: true
          right:
            value:
              simple: "30"
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: b414ac44-f5f7-4dbb-8166-37f382d9e0a3
    type: regular
    task:
      id: b414ac44-f5f7-4dbb-8166-37f382d9e0a3
      version: -1
      name: Set
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      key:
        simple: ValidationKey
      stringify:
        simple: "true"
      value:
        simple: ThisisaBurstTestfromInstance${incident.name}FromSlack
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: 5f84d6f3-1d56-49b2-8397-fb8fea43db46
    type: regular
    task:
      id: 5f84d6f3-1d56-49b2-8397-fb8fea43db46
      version: -1
      name: Set
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      key:
        simple: RunStatus
      value:
        simple: completed
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1800
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1845,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 6.1.0
description: Used to send messages to a mirrored channel on Slack and validate they
  were mirrored into XSOAR.
