id: CheckLogin
version: -1
name: CheckLogin
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: bb47b102-e26e-4d3d-80ea-d0d6bccf08a1
    type: start
    task:
      id: bb47b102-e26e-4d3d-80ea-d0d6bccf08a1
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: c88d0a4c-57e3-4d18-8a64-1355cca44f7b
    type: title
    task:
      id: c88d0a4c-57e3-4d18-8a64-1355cca44f7b
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: e5293b1d-307c-46f2-8367-c15536e33fb5
    type: regular
    task:
      id: e5293b1d-307c-46f2-8367-c15536e33fb5
      version: -1
      name: check-login
      description: can smithers login successfully?
      script: '|||check-login'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      password:
        simple: "1234"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 385,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs:
- contextPath: MrBurns.Present
  description: What a nice present.
  type: string
