id: Escape Room - Phase 2
version: -1
name: Escape Room - Phase 2
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: f07c9c17-1fbb-4a21-8d5a-e950af0258a2
    type: start
    task:
      id: f07c9c17-1fbb-4a21-8d5a-e950af0258a2
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 65
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 7fefbcdd-f58f-49e1-8aac-ca204b12299e
    type: playbook
    task:
      id: 7fefbcdd-f58f-49e1-8aac-ca204b12299e
      version: -1
      name: WhenIsNextNext
      playbookName: WhenIsNextNext
      type: playbook
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "6"
    separatecontext: true
    loop:
      iscommand: false
      builtincondition:
      - - operator: isEqualString
          left:
            value:
              simple: NextNext
            iscontext: true
          right:
            value:
              simple: Correct
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 50,
          "y": 575
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 7e8749ba-2fda-45f3-8216-d6050aae9bac
    type: regular
    task:
      id: 7e8749ba-2fda-45f3-8216-d6050aae9bac
      version: -1
      name: Print instructions
      description: Prints text to war room (Markdown supported)
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      value:
        simple: 'I got this info from a customer and I don''t know what to do with
          it: dHlwZTpQb3dlclNoZWxsIC10YWdzOmluZnJhLEpTT04='
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 225
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 2
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: c3af41d9-7659-4f4a-8da7-53aed1d11f26
    type: regular
    task:
      id: c3af41d9-7659-4f4a-8da7-53aed1d11f26
      version: -1
      name: Print instructions
      description: Prints text to war room (Markdown supported)
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      value:
        simple: In the next task, you need to push your answer to the Context Data
          under the key WhenIsNextNext and mark the task as completed in order to
          check whether your answer is correct. The date format is YYYY-MM-DDThh:mm
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 400
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 2
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 844291ec-4146-46fd-8a85-827ea1027db4
    type: regular
    task:
      id: 844291ec-4146-46fd-8a85-827ea1027db4
      version: -1
      name: Print instructions
      description: Prints text to war room (Markdown supported)
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      value:
        simple: In the next task, you need to push your answer to the Context Data
          under the key WhoAmI and mark the task as completed in order to check whether
          your answer is correct
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 750
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 2
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: e49d7133-0159-4d86-8af0-cb5d2a405ad5
    type: playbook
    task:
      id: e49d7133-0159-4d86-8af0-cb5d2a405ad5
      version: -1
      name: WhoAmI
      playbookName: WhoAmI
      type: playbook
      iscommand: false
      brand: ""
    scriptarguments:
      value:
        simple: ${WhoAmI}
    separatecontext: true
    loop:
      iscommand: false
      builtincondition:
      - - operator: isEqualString
          left:
            value:
              simple: Me
            iscontext: true
          right:
            value:
              simple: Wow
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 50,
          "y": 925
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
system: true
locked: true
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 955,
        "width": 380,
        "x": 50,
        "y": 65
      }
    }
  }
inputs: []
outputs: []
quiet: true
