id: WhenIsNextNext
version: -1
name: WhenIsNextNext
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: bb47b102-e26e-4d3d-80ea-d0d6bccf08a1
    type: start
    task:
      id: bb47b102-e26e-4d3d-80ea-d0d6bccf08a1
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "8"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 630f1d9e-2506-46b2-841a-5b173cb5de80
    type: condition
    task:
      id: 630f1d9e-2506-46b2-841a-5b173cb5de80
      version: -1
      name: Are the answers correct?
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries} to check the previous task entries. If array is provided, will return yes if one of the entries returned an error.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: WhenIsNextNextAnswer
            iscontext: true
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 3be1ab25-2970-4db4-8031-ed2313d29b45
    type: regular
    task:
      id: 3be1ab25-2970-4db4-8031-ed2313d29b45
      version: -1
      name: You are correct!
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      key:
        simple: NextNext
      value:
        simple: Correct
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 550
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: f57e1999-f0f0-4b27-89d2-b863df052b68
    type: title
    task:
      id: f57e1999-f0f0-4b27-89d2-b863df052b68
      version: -1
      name: Set score
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: c88d0a4c-57e3-4d18-8a64-1355cca44f7b
    type: title
    task:
      id: c88d0a4c-57e3-4d18-8a64-1355cca44f7b
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 865
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 05beb823-eca1-443a-8f10-b1c1a644cdb5
    type: regular
    task:
      id: 05beb823-eca1-443a-8f10-b1c1a644cdb5
      version: -1
      name: when-is-next-next
      description: run to find hints
      script: '|||when-is-next-next'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      answer:
        simple: ${input.value}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 880,
        "width": 595,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: value
  value:
    simple: ${WhenIsNextNext}
  required: false
  description: ""
  playbookInputQuery:
outputs:
- contextPath: NextNext
  description: Whether answers are correct or not.
  type: string
tests:
- No tests (auto formatted)
fromversion: 6.0.0
description: ''
