description: test playbook for hashIncidentFields
id: hashIncidentFields-test
inputs: []
name: hashIncidentFields-test
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: start
      id: dd9e4f59-1a0f-4bc2-85fd-288e055c2ddc
      iscommand: false
      name: ""
      version: -1
    taskid: dd9e4f59-1a0f-4bc2-85fd-288e055c2ddc
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      numberOfIncidents:
        simple: "50"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Create incidents for test
      id: f0bb619e-6c07-4991-8700-44d9d215fbaa
      iscommand: false
      name: CreateIncidents
      script: CreateIncidentsForEvaluateMLModllAtProduction
      type: regular
      version: -1
    taskid: f0bb619e-6c07-4991-8700-44d9d215fbaa
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      contextKeys:
        simple: simpleValue, listValue
      includeContext:
        simple: "true"
      outputFormat:
        simple: json
      query:
        simple: ${IncidentsQuery}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get incidents and hash some fields
      id: 8433c4e5-3c9a-40e0-825b-2f2f3c2415f8
      iscommand: false
      name: HashIncidentsFields
      script: HashIncidentsFields
      type: regular
      version: -1
    taskid: 8433c4e5-3c9a-40e0-825b-2f2f3c2415f8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Done
      id: 90c6a67d-280a-4186-8569-4cef5f36b46e
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 90c6a67d-280a-4186-8569-4cef5f36b46e
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "4":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: HashIncidentsFields.Filename
          operator: isNotEmpty
      label: "yes"
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "yes":
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if the file was created
      id: e798c47b-1aaa-436b-879c-f75171037b22
      iscommand: false
      name: File created ?
      type: condition
      version: -1
    taskid: e798c47b-1aaa-436b-879c-f75171037b22
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Delete field from context
      id: 26b37cc2-6edc-4e27-83cb-2efc77d0fb11
      iscommand: false
      name: Clean Context
      script: DeleteContext
      type: regular
      version: -1
    taskid: 26b37cc2-6edc-4e27-83cb-2efc77d0fb11
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "4_3_yes": 0.53
    },
    "paper": {
      "dimensions": {
        "height": 910,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
