contentitemexportablefields:
  contentitemfields:
    propagationLabels:
    - all
id: Questionnaire - 1
inputs: []
name: Questionnaire - 1
outputs:
- contextPath: Questionnaire.Time.Answers
  description: Whether answers are correct or not.
  type: string
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 44c49dc4-c86f-4e02-8b15-5e5ad761aada
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 44c49dc4-c86f-4e02-8b15-5e5ad761aada
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 40
        }
      }
  "1":
    form:
      description: ""
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: When should we schedule our morning coffee?
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: true
        tooltip: ""
        type: shortText
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "1"
        label: ""
        labelarg:
          simple: Who are our early dev-birds (one per team)?
        options: []
        optionsarg:
        - simple: Yuval Ben-Shalom, Shai Yaakovi, Rony Kozakish, Itay Keren
        - simple: Bar Katzir, Bar Genish, Bar Chen, Bar Hochman
        - simple: Orel Haim, Adi Daud, Dan Tavori, Itay Keren
        - simple: Yana Orhov, Eli Sharf, Guy Keller, Itay Keren
        - simple: Jasmine Beilin, Noy Maimon, Aviya Baumgarten, Darya Koval
        placeholder: ""
        readonly: false
        required: true
        tooltip: ""
        type: singleSelect
      sender: ""
      title: Content - Office Hours
      totalanswers: 0
    id: "1"
    ignoreworker: false
    message:
      bcc:
      body:
        simple: hello
      cc:
      format: ""
      methods:
      - email
      subject:
        simple: hello
      timings:
        completeafterreplies: 1
        retriescount: 2
        retriesinterval: 360
      to:
        simple: Administrator
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 649334a4-6a2d-4504-837e-67effae019c5
      iscommand: false
      name: Questionnaire - 1
      type: collection
      version: -1
    taskid: 649334a4-6a2d-4504-837e-67effae019c5
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
  "2":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: "0"
                root: Content - Office Hours.Answers
          operator: isEqualString
          right:
            value:
              simple: "09:00"
      - - left:
            iscontext: true
            value:
              complex:
                accessor: "1"
                root: Content - Office Hours.Answers
          operator: isEqualString
          right:
            value:
              simple: Yana Orhov, Eli Sharf, Guy Keller, Itay Keren
      label: "yes"
    id: "2"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6076b6b9-bea9-4438-8276-96dced287576
      iscommand: false
      name: Is the answers correct?
      type: condition
      version: -1
    taskid: 6076b6b9-bea9-4438-8276-96dced287576
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      append: {}
      key:
        simple: Questionnaire.Time.Answers
      stringify: {}
      value:
        simple: Correct
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 128298bd-0aad-4ecd-8827-cd6f47cb2003
      iscommand: false
      name: You are correct!
      script: Set
      type: regular
      version: -1
    taskid: 128298bd-0aad-4ecd-8827-cd6f47cb2003
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      append: {}
      key:
        simple: Questionnaire.Time.Answers
      stringify: {}
      value:
        simple: Incorrect
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 67a6bb00-4e02-4f6d-845a-314b9167313e
      iscommand: false
      name: Incorrect stupid
      script: Set
      type: regular
      version: -1
    taskid: 67a6bb00-4e02-4f6d-845a-314b9167313e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 176b0d70-1bcd-4893-813e-fa84debb7293
      iscommand: false
      name: Set score
      type: title
      version: -1
      description: ''
    taskid: 176b0d70-1bcd-4893-813e-fa84debb7293
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
  "6":
    id: "6"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 200f3581-7e9f-4cb6-8800-8a45c4c60177
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: 200f3581-7e9f-4cb6-8800-8a45c4c60177
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1050
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "no"
      index: {}
      key:
        simple: Content - Office Hours
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Delete field from context
      id: 8f8247f2-f949-4e18-81e3-bc26f677fb78
      iscommand: false
      name: Delete Context
      script: DeleteContext
      type: regular
      version: -1
    taskid: 8f8247f2-f949-4e18-81e3-bc26f677fb78
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 185
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1075,
        "width": 810,
        "x": 50,
        "y": 40
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
description: ''
