contentitemexportablefields:
  contentitemfields:
    propagationLabels:
    - all
id: Escape Room - Phase 1
inputs: []
name: Escape Room - Phase 1
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0daaccb4-2ed4-457b-8c3c-29c3d1ce6331
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 0daaccb4-2ed4-457b-8c3c-29c3d1ce6331
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: |-
          ![](https://media.giphy.com/media/2S3Aj8OeKtf0c/giphy.gif)
          No time to waste, we are on a tight schedule!
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 56bcea12-b87c-4837-8ee6-e9d895765bf5
      iscommand: false
      name: The clock is ticking
      script: Print
      type: regular
      version: -1
    taskid: 56bcea12-b87c-4837-8ee6-e9d895765bf5
    timertriggers:
    - action: start
      fieldname: escaperoomsla
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 880c097e-9a08-436b-818d-302b38a24fea
      iscommand: false
      name: Welcome
      script: c0fd5a15-f4d1-482d-8bf3-419b7ca0e047
      type: regular
      version: -1
    taskid: 880c097e-9a08-436b-818d-302b38a24fea
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      seconds:
        simple: "3"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sleep for X seconds
      id: f2063213-99eb-4e6d-889a-ef0e3b57eacf
      iscommand: false
      name: Wait for it - *change
      script: Sleep
      type: regular
      version: -1
    taskid: f2063213-99eb-4e6d-889a-ef0e3b57eacf
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e714b683-6651-48f1-89df-99766e5a1209
      iscommand: false
      name: yay
      type: title
      version: -1
      description: ''
    taskid: e714b683-6651-48f1-89df-99766e5a1209
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 910
        }
      }
  "8":
    id: "8"
    ignoreworker: false
    loop:
      exitCondition: "yes"
      iscommand: false
      max: 100
      scriptArguments:
        left:
          complex:
            accessor: Answers
            root: Questionnaire.Time
        right:
          simple: Correct
      scriptId: AreValuesEqual
      wait: 1
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 672ac42d-2f4a-45e0-8792-a8dd3811abf2
      iscommand: false
      name: d0cd9137-6694-4ad5-8a51-4a75a76c5cec
      playbookId: d0cd9137-6694-4ad5-8a51-4a75a76c5cec
      script: AreValuesEqual
      type: playbook
      version: -1
      description: ''
    taskid: 672ac42d-2f4a-45e0-8792-a8dd3811abf2
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 730
        }
      }
  "9":
    id: "9"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: '"You are a prince!"'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 96905957-2b39-47d5-8cf8-e53606f35913
      iscommand: false
      name: Print
      script: Print
      type: regular
      version: -1
    taskid: 96905957-2b39-47d5-8cf8-e53606f35913
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1115,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
description: ''
