id: Escape Room - Phase 1
version: -1
name: Escape Room - Phase 1
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 4581b7dd-1819-44dc-8aaa-b8296108f1dc
    type: start
    task:
      id: 4581b7dd-1819-44dc-8aaa-b8296108f1dc
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: fc533ac7-db74-4bbd-86f3-82a3e7b5f9dd
    type: regular
    task:
      id: fc533ac7-db74-4bbd-86f3-82a3e7b5f9dd
      version: -1
      name: The clock is ticking
      description: Prints text to war room (Markdown supported)
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      value:
        simple: |-
          ![](https://media.giphy.com/media/2S3Aj8OeKtf0c/giphy.gif)
          No time to waste, we are on a tight schedule!
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers:
    - fieldname: escaperoomsla
      action: start
    ignoreworker: false
    skipunavailable: false
    quietmode: 2
  "4":
    id: "4"
    taskid: 23c0f528-04da-4ced-87f7-46a312415f3c
    type: regular
    task:
      id: 23c0f528-04da-4ced-87f7-46a312415f3c
      version: -1
      name: Welcome
      scriptName: Welcome
      type: regular
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#none#':
      - "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 2
  "5":
    id: "5"
    taskid: 4fde1b39-6f37-48e4-80b1-0a4ced10a74d
    type: regular
    task:
      id: 4fde1b39-6f37-48e4-80b1-0a4ced10a74d
      version: -1
      name: Wait for it - *change
      description: Sleep for X seconds
      scriptName: Sleep
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      seconds:
        simple: "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: aca75999-30f9-48e5-85dd-8935a5d59890
    type: title
    task:
      id: aca75999-30f9-48e5-85dd-8935a5d59890
      version: -1
      name: yay
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "9"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 910
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: 7da59123-e6b6-493e-8b7d-385443d415c3
    type: playbook
    task:
      id: 7da59123-e6b6-493e-8b7d-385443d415c3
      version: -1
      name: Questionnaire - 1
      playbookName: Questionnaire - 1
      scriptName: AreValuesEqual
      type: playbook
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "7"
    results:
    - AreValuesEqual
    separatecontext: false
    loop:
      iscommand: false
      scriptArguments:
        left:
          complex:
            root: Questionnaire.Time
            accessor: Answers
        right:
          simple: Correct
      exitCondition: "yes"
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 50,
          "y": 730
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: c80001d7-ed6e-4f2b-8e57-432e6d404465
    type: regular
    task:
      id: c80001d7-ed6e-4f2b-8e57-432e6d404465
      version: -1
      name: Print
      description: Prints text to war room (Markdown supported)
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      value:
        simple: '"You are a prince!"'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1115,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
description: ''
