id: Symantec Data Loss Prevention v2 - Test
version: -1
name: Symantec Data Loss Prevention v2 - Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 70bedcb9-4600-40ef-8b05-632e5c62f1e6
    type: start
    task:
      id: 70bedcb9-4600-40ef-8b05-632e5c62f1e6
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: db52c03a-c3eb-4853-85b2-de9c8ddc4aba
    type: regular
    task:
      id: db52c03a-c3eb-4853-85b2-de9c8ddc4aba
      version: -1
      name: Get incidents list
      description: Returns a list of incidents.
      script: '|||symantec-dlp-list-incidents'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      limit:
        simple: "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 409d8652-cb6e-4dec-8351-8f2aa876c419
    type: regular
    task:
      id: 409d8652-cb6e-4dec-8351-8f2aa876c419
      version: -1
      name: Get incidents status list
      description: Returns a list of the custom status values defined in the Symantec
        DLP deployment.
      script: '|||symantec-dlp-list-incident-status'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 6a8832aa-7aee-48c9-83d0-ba56c73e5853
    type: regular
    task:
      id: 6a8832aa-7aee-48c9-83d0-ba56c73e5853
      version: -1
      name: Get remediation status
      description: Returns a list of the remediation status values defined in the
        Symantec DLP deployment.
      script: '|||symantec-dlp-list-remediation-status'
      type: regular
      iscommand: true
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 2750772f-2163-456d-8bb2-ba505b2b8abb
    type: regular
    task:
      id: 2750772f-2163-456d-8bb2-ba505b2b8abb
      version: -1
      name: Get incident details
      description: Returns the details of the specified incident.
      script: '|||symantec-dlp-get-incident-details'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      incident_id:
        complex:
          root: SymantecDLP.Incident
          accessor: ID
          transformers:
          - operator: atIndex
            args:
              index:
                value:
                  simple: "0"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 01f74aa9-1b87-4823-8adc-9afb0ed3229f
    type: regular
    task:
      id: 01f74aa9-1b87-4823-8adc-9afb0ed3229f
      version: -1
      name: Get incident history
      description: Returns the history of the specified incident.
      script: '|||symantec-dlp-get-incident-history'
      type: regular
      iscommand: true
      brand: ""
    scriptarguments:
      incident_id:
        simple: ${SymantecDLP.Incident.ID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 590,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 6.0.0
description: ''
